export default [
  {
    name: 'Artemis',
    class: 0,
    race: 'Human',
    initiative: 50,
    agility: 75,
    weaponsSpeed: 50,
    firePower: 1,
    fireRate: 10,
    quantityOfWeapons: 1,
    damageType: 'Normal',
    fuselage: 10,
    empResistance: 0,
  },
  {
    name: 'Perseus',
    class: 1,
    race: 'Human',
    initiative: 50,
    agility: 60,
    weaponsSpeed: 50,
    firePower: 5,
    fireRate: 2,
    quantityOfWeapons: 2,
    damageType: 'Normal',
    fuselage: 20,
    empResistance: 5,
  },
  {
    name: 'Hera',
    class: 1,
    race: 'Human',
    initiative: 50,
    agility: 60,
    weaponsSpeed: 50,
    firePower: 3,
    fireRate: 2,
    quantityOfWeapons: 5,
    damageType: 'Normal',
    fuselage: 30,
    empResistance: 5,
  },
  {
    name: 'Demeter',
    class: 2,
    race: 'Human',
    initiative: 50,
    agility: 45,
    weaponsSpeed: 50,
    firePower: 3,
    fireRate: 10,
    quantityOfWeapons: 2,
    damageType: 'Normal',
    fuselage: 60,
    empResistance: 10,
  },
  {
    name: 'Vulcan',
    class: 2,
    race: 'Human',
    initiative: 50,
    agility: 45,
    weaponsSpeed: 50,
    firePower: 10,
    fireRate: 2,
    quantityOfWeapons: 4,
    damageType: 'Normal',
    fuselage: 80,
    empResistance: 10,
  },
  {
    name: 'Ares',
    class: 2,
    race: 'Human',
    initiative: 50,
    agility: 45,
    weaponsSpeed: 50,
    firePower: 20,
    fireRate: 5,
    quantityOfWeapons: 1,
    damageType: 'Normal',
    fuselage: 100,
    empResistance: 10,
  },
  {
    name: 'Thanatos',
    class: 3,
    race: 'Human',
    initiative: 50,
    agility: 30,
    weaponsSpeed: 50,
    firePower: 10,
    fireRate: 3,
    quantityOfWeapons: 5,
    damageType: 'Normal',
    fuselage: 150,
    empResistance: 15,
  },
  {
    name: 'Neptune',
    class: 3,
    race: 'Human',
    initiative: 50,
    agility: 30,
    weaponsSpeed: 50,
    firePower: 1,
    fireRate: 1,
    quantityOfWeapons: 4,
    damageType: 'Roids',
    fuselage: 150,
    empResistance: 15,
  },
  {
    name: 'Hermes',
    class: 4,
    race: 'Human',
    initiative: 50,
    agility: 15,
    weaponsSpeed: 50,
    firePower: 5,
    fireRate: 5,
    quantityOfWeapons: 8,
    damageType: 'Normal',
    fuselage: 200,
    empResistance: 20,
  },
  {
    name: 'Apollo',
    class: 4,
    race: 'Human',
    initiative: 50,
    agility: 15,
    weaponsSpeed: 50,
    firePower: 15,
    fireRate: 10,
    quantityOfWeapons: 2,
    damageType: 'Normal',
    fuselage: 300,
    empResistance: 20,
  },
  {
    name: 'Hercules',
    class: 5,
    race: 'Human',
    initiative: 50,
    agility: 0,
    weaponsSpeed: 50,
    firePower: 5,
    fireRate: 5,
    quantityOfWeapons: 20,
    damageType: 'Normal',
    fuselage: 500,
    empResistance: 25,
  },
  {
    name: 'Zeus',
    class: 5,
    race: 'Human',
    initiative: 50,
    agility: 0,
    weaponsSpeed: 50,
    firePower: 250,
    fireRate: 1,
    quantityOfWeapons: 3,
    damageType: 'Normal',
    fuselage: 750,
    empResistance: 25,
  },
  {
    name: 'Osiris',
    class: 0,
    race: 'Daharan',
    initiative: 50,
    agility: 75,
    weaponsSpeed: 50,
    firePower: 5,
    fireRate: 1,
    quantityOfWeapons: 1,
    damageType: 'EMP',
    fuselage: 5,
    empResistance: 5,
  },
  {
    name: 'Isis',
    class: 0,
    race: 'Daharan',
    initiative: 50,
    agility: 75,
    weaponsSpeed: 50,
    firePower: 5,
    fireRate: 1,
    quantityOfWeapons: 2,
    damageType: 'EMP',
    fuselage: 10,
    empResistance: 5,
  },
  {
    name: 'Horus',
    class: 1,
    race: 'Daharan',
    initiative: 50,
    agility: 60,
    weaponsSpeed: 50,
    firePower: 10,
    fireRate: 1,
    quantityOfWeapons: 2,
    damageType: 'EMP',
    fuselage: 20,
    empResistance: 10,
  },
  {
    name: 'Set',
    class: 1,
    race: 'Daharan',
    initiative: 50,
    agility: 60,
    weaponsSpeed: 50,
    firePower: 10,
    fireRate: 1,
    quantityOfWeapons: 3,
    damageType: 'EMP',
    fuselage: 30,
    empResistance: 10,
  },
  {
    name: 'Geb',
    class: 1,
    race: 'Daharan',
    initiative: 50,
    agility: 60,
    weaponsSpeed: 50,
    firePower: 20,
    fireRate: 1,
    quantityOfWeapons: 2,
    damageType: 'EMP',
    fuselage: 40,
    empResistance: 10,
  },
  {
    name: 'Bastet',
    class: 2,
    race: 'Daharan',
    initiative: 50,
    agility: 45,
    weaponsSpeed: 50,
    firePower: 20,
    fireRate: 1,
    quantityOfWeapons: 4,
    damageType: 'EMP',
    fuselage: 80,
    empResistance: 15,
  },
  {
    name: 'Nut',
    class: 3,
    race: 'Daharan',
    initiative: 50,
    agility: 30,
    weaponsSpeed: 50,
    firePower: 80,
    fireRate: 1,
    quantityOfWeapons: 2,
    damageType: 'EMP',
    fuselage: 160,
    empResistance: 20,
  },
  {
    name: 'Sekhmet',
    class: 4,
    race: 'Daharan',
    initiative: 50,
    agility: 15,
    weaponsSpeed: 50,
    firePower: 50,
    fireRate: 1,
    quantityOfWeapons: 6,
    damageType: 'EMP',
    fuselage: 300,
    empResistance: 25,
  },
  {
    name: 'Anubis',
    class: 4,
    race: 'Daharan',
    initiative: 50,
    agility: 15,
    weaponsSpeed: 50,
    firePower: 200,
    fireRate: 1,
    quantityOfWeapons: 2,
    damageType: 'EMP',
    fuselage: 400,
    empResistance: 25,
  },
  {
    name: 'Thoth',
    class: 4,
    race: 'Daharan',
    initiative: 50,
    agility: 15,
    weaponsSpeed: 50,
    firePower: 1,
    fireRate: 1,
    quantityOfWeapons: 5,
    damageType: 'Roids',
    fuselage: 400,
    empResistance: 25,
  },
  {
    name: 'Nephthys',
    class: 5,
    race: 'Daharan',
    initiative: 50,
    agility: 0,
    weaponsSpeed: 50,
    firePower: 100,
    fireRate: 1,
    quantityOfWeapons: 6,
    damageType: 'EMP',
    fuselage: 600,
    empResistance: 30,
  },
  {
    name: 'Amun-Ra',
    class: 5,
    race: 'Daharan',
    initiative: 50,
    agility: 0,
    weaponsSpeed: 50,
    firePower: 800,
    fireRate: 1,
    quantityOfWeapons: 1,
    damageType: 'EMP',
    fuselage: 800,
    empResistance: 30,
  },
];
